version: "3"

services:
  netflix:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/conf
      - ./logs:/app/logs
    container_name: netflix
    networks:
      - netflix-network
    restart: always
  redis:
    image: redis:6.2.6-bullseye
    volumes:
      - redis-for-netflix-data:/data
    container_name: redis_for_netflix
    networks:
      - netflix-network
    restart: always

volumes:
  redis-for-netflix-data:

networks:
  netflix-network:
    driver: bridge
